name: CI

on:
    push:
        branches: [main]

jobs:
    detect:
        name: Detect
        runs-on: ubuntu-latest

        steps:
            - name: Detect Android NDK version
              run: |
                  $ANDROID_HOME/tools/bin/sdkmanager --list
