name: Detox Android CI

on:
    push:
        branches: [main]

jobs:
    ci:
        name: Detox Android CI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  clean: false

            - name: Setup Java
              uses: actions/setup-java@v1
              with:
                  java-version: '8'
                  java-package: jdk
                  architecture: x64

            - name: Node
              uses: actions/setup-node@v1

            - name: Install Emulator Image
              run: |
                  echo y | $ANDROID_HOME/tools/bin/sdkmanager --update
                  echo y | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;default;x86"

            - name: Create Emulator
              run: |
                  $ANDROID_HOME/tools/bin/sdkmanager --update 
                  echo "no" | $ANDROID_HOME/tools/bin/avdmanager --verbose create avd --force --name "test" --package "system-images;android-29;default;x86" --tag "default" --abi "x86"

            - name: Change Emulator location
              run: |
                  rm -rf $ANDROID_HOME/emulator/emulator

            - name: Install pulseaudio
              run: sudo apt-get install pulseaudio

            - name: Install dependencies
              run: |
                  cd packages/app
                  yarn install

            - name: Build for Detox
              run: |
                  cd packages/app
                  cd android && chmod +x ./gradlew
                  cd ..
                  yarn e2e:build:ci

            - name: Android Detox
              run: |
                  export ANDROID_SDK_ROOT=$ANDROID_HOME
                  cd packages/app
                  yarn e2e:ci
